# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e4a624a3256fa6236f2aee6ab95a73cd1bd9f5d460ab23b85675de1c4594c6dc74abe95a15147ca64ad0d9489ee95c9172ea868786821254718d9f9c704064

test:
  secret_key_base: 0d7ba58f04ffce9028d5debb5ffc07aaf274feae826c7b865f4cb222974dca1a52c7b79fefca68b11f3315d0c046c20a4a8dcd9fad2bc61443a2afcbe8b87623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
